### ISSUE TITLE
Analyzer manager failed to retrieve bin file to map()

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#1657]
Please see this PR and also copy/paste issue below
https://github.com/InstituteforDiseaseModeling/malaria-mmc-diagnostics-idmtools/pull/11

prevalence_analyzer.py fail with error:

C:\mnc_idmtools_37\Scripts\python.exe C:/github/malaria-mmc-diagnostics-idmtools/simulation/analyzers/run_prevalence_analyzer.py
/!\ WARNING: File 'idmtools.ini' Not Found! For details on how to configure idmtools, see https://docs.idmod.org/projects/idmtools/en/v1.6.4/configuration.html for details on how to configure idmtools.

[BELEGOST]
{
   "endpoint": "https://comps.idmod.org",
   "environment": "Belegost"
}
  0%|          | 0/5000 [00:00<?, ?it/s]Analyze Manager
 | 5000 item(s) selected for analysis
 | partial_analyze_ok is False, max_items is None, and 0 item(s) are being ignored
 | Analyzer(s): 
 |  - PrevalenceAnalyzer File parsing: on / Use cache: off
 | Pool of 8 analyzing process(es)
100%|█████████▉| 4981/5000 [00:12<00:00, 632.28it/s]C:\mnc_idmtools_37\lib\site-packages\idmtools\entities\iplatform.py:121: UserWarning: Please use Factory to create Platform! For example: 
    platform = Platform('COMPS', **kwargs)
  warnings.warn("Please use Factory to create Platform! For example: \n    platform = Platform('COMPS', **kwargs)")
100%|██████████| 5000/5000 [00:14<00:00, 344.40it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\python37\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\mnc_idmtools_37\lib\site-packages\idmtools\analysis\map_worker_entry.py", line 41, in map_item
    return _get_mapped_data_for_item(item, analyzers, platform)
  File "C:\mnc_idmtools_37\lib\site-packages\idmtools\analysis\map_worker_entry.py", line 101, in _get_mapped_data_for_item
    raise e
  File "C:\mnc_idmtools_37\lib\site-packages\idmtools\analysis\map_worker_entry.py", line 92, in _get_mapped_data_for_item
    selected_data[analyzer.uid] = analyzer.map(data, item)
  File "C:\github\malaria-mmc-diagnostics-idmtools\simulation\analyzers\prevalence_analyzer.py", line 49, in map
    data[f'output/SpatialReportMalariaFiltered_{self.spatial_channels[0]}.bin'], self.spatial_channels[0])
  File "C:\github\malaria-mmc-diagnostics-idmtools\simulation\analyzers\prevalence_analyzer.py", line 8, in construct_spatial_output_df
    n_nodes = rawdata['n_nodes']
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/github/malaria-mmc-diagnostics-idmtools/simulation/analyzers/run_prevalence_analyzer.py", line 30, in <module>
    manager.analyze()
  File "C:\mnc_idmtools_37\lib\site-packages\idmtools\analysis\analyze_manager.py", line 457, in analyze
    map_results, status = self._run_and_wait_for_mapping(executor)
  File "C:\mnc_idmtools_37\lib\site-packages\idmtools\analysis\analyze_manager.py", line 338, in _run_and_wait_for_mapping
    raise ex
TypeError: 'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
Process finished with exit code 1
This is due to a bug in idmtools which can not load bin file to map's data (still reference dtk)
https://github.com/InstituteforDiseaseModeling/idmtools/blob/240f8095a494fa4f2cccf235fb82b92d8e47f195/idmtools_core/idmtools/analysis/map_worker_entry.py#L85
https://github.com/InstituteforDiseaseModeling/idmtools/blob/240f8095a494fa4f2cccf235fb82b92d8e47f195/idmtools_core/idmtools/utils/file_parser.py#L51
https://github.com/InstituteforDiseaseModeling/idmtools/blob/240f8095a494fa4f2cccf235fb82b92d8e47f195/idmtools_core/idmtools/utils/file_parser.py#L146

**Comment by shchen-idmod** [comment]
Add reference: https://github.com/InstituteforDiseaseModeling/malaria-mmc-diagnostics-idmtools/pull/41/files
https://github.com/InstituteforDiseaseModeling/malaria-mmc-diagnostics-idmtools/blob/main/simulation/utils/spatial_output.py

**Comment by devclinton** [comment]
This ticket should be addressed at the same time as #1657

**Comment by shchen-idmod** [comment]
Fixed in #2149
