### ISSUE TITLE
Failure Recovery - analyze_manager.py -  calibration in progress was interrupted 

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/idmtools#1660]
## SUMMARY
CONTEXT: During the execution of a calibration job for HIV, there was a failure which killed my job: 
![image](https://user-images.githubusercontent.com/74386190/143152719-aa1580b4-80f3-4bb9-8cf3-bc100c5df06f.png)

.     .    .

![image](https://user-images.githubusercontent.com/74386190/143143880-ca2daf59-0eeb-4e3b-acfa-0714465404dc.png)
The issue happened at 3 am, so the client from which I submitted the job was unattended.

So we may have two issues, 
### **_"Tcl_AsyncDelete: async handler deleted by the wrong thread"_**
- the first one: the actual bug in the analyze_manager.py script, for which I am not sure I have enough information to provide other than the command executed: 

```
python -m hiv_workflow.scripts.calibrate -m baseline -o calibration/output/3/ -N DebuggingCalibrationEffectivity -i 50 -r 2 -c 2 
 -n 5 optim_tool
```

- For more information, please refer to the instructions (demo) page: (command # 2) https://github.com/InstituteforDiseaseModeling/hiv_workflow/blob/main/examples/rakai-optimtool/demo.md ) - (Hopefully you can diagnose based on the limited information in this bug)
-Also, the ingest file that was used was slightly modified from the original one located at: <repo dir>\hiv_workflow\examples\rakai-optimtool\calibration\ingest_forms: [calibration_ingest_form--testing.zip](https://github.com/InstituteforDiseaseModeling/idmtools/files/7591707/calibration_ingest_form--testing.zip)
( only the calibration parameters and guess values were updated)

## Issue 2: 

- The second issue and more important one, is the way how the system recovers from a failure. The simulations are submitted individually, and if a single simulation fails, it doesn't seem to be a way to automatically recover from it (i.e.  a retry of the last task, a "finally" statement, etc.) - This may be an architectural change to the way how the tasks are dispatched / handled and considered successfully executed, on the client side -  

- NOTE: Attached is the log file:  [idmtools.log](https://github.com/InstituteforDiseaseModeling/idmtools/files/7591661/idmtools.log)

 

- Corresponding COMPS suite:  https://comps.idmod.org/#explore/Suites?filters=Id=58f90d57-264c-ec11-a9f1-9440c9be2c51&selectedId=58f90d57-264c-ec11-a9f1-9440c9be2c51&mode=list&orderby=DateCreated%20desc&count=100&offset=0 

## Error
WARNING: During schema-based param purge, Enable_Continuous_Log_Flushing not in schema.
WARNING: During schema-based param purge, logLevel_default not in schema.
WARNING: During schema-based param purge, Disable_IP_Whitelist not in schema.
WARNING: During schema-based param purge, Enable_Continuous_Log_Flushing not in schema.
WARNING: During schema-based param purge, logLevel_default not in schema.
Creating Simulations on Comps: 100%|██████████| 10/10 [00:01<00:00,  6.03simulation/s]
  0%|          | 0/10 [00:00<?, ?it/s]Tcl_AsyncDelete: async handler deleted by the wrong thread
100%|██████████| 10/10 [00:51<00:00,  5.16s/it]
A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools\analysis\analyze_manager.py", line 457, in analyze
    map_results, status = self._run_and_wait_for_mapping(executor)
  File "C:\GIT\CLARK\hiv_workflow\

VENV-HIV-WORKFLOW\lib\site-packages\idmtools\analysis\analyze_manager.py", line 338, in _run_and_wait_for_mapping
    raise ex
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
python-BaseException
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\pydevd.py", line 2173, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/GIT/CLARK/hiv_workflow/examples/rakai-optimtool/start.py", line 17, in <module>
    x.main(args)
  File "C:\GIT\CLARK\hiv_workflow\hiv_workflow\scripts\calibrate.py", line 100, in main
    calib_manager.run_calibration()
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools_calibra\calib_manager.py", line 170, in run_calibration
    self.run_iterations()
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools_calibra\calib_manager.py", line 189, in run_iterations
    self.current_iteration.run()
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools_calibra\iteration_state.py", line 122, in run
    self.analyze_step()
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools_calibra\iteration_state.py", line 161, in analyze_step
    self.analyze_iteration()
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools_calibra\iteration_state.py", line 235, in analyze_iteration
    if not analyzerManager.analyze():
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools\analysis\analyze_manager.py", line 457, in analyze
    map_results, status = self._run_and_wait_for_mapping(executor)
  File "C:\GIT\CLARK\hiv_workflow\VENV-HIV-WORKFLOW\lib\site-packages\idmtools\analysis\analyze_manager.py", line 338, in _run_and_wait_for_mapping
    raise ex
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
python-BaseException

Process finished with exit code 1

**Comment by devclinton** [comment]
Try to reproduce
Then identify root cause

**Comment by devclinton** [comment]
This ticket is super old. Do we know is resuming is still difficult with calibration @ZDu-IDM @ckirkman-IDM @shchen-idmod ?

**Comment by shchen-idmod** [comment]
I do not think we have resume issue anymore.
